# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0002_auto_20170309_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcaveiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipoveiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='Veículo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo do Veículo')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa do Veículo')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor do Veículo')),
                ('Id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Marcaveiculo')),
                ('Id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Tipoveiculo')),
            ],
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='Id_cargo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='Id_pessoa',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
