# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0003_auto_20170329_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veículo',
            new_name='Veiculo',
        ),
    ]
